# This will be the first part of the title tag for your site <title> site.name + page.title </title>
title: "DINGYONG"
description: "Professional manufacturer of stainless steel cutlery, flatware and kitchen tools for hotels, restaurants and retail brands"
email: sales@ding-yong.com
url: "https://www.ding-yong.com" # the base hostname & protocol for your site, e.g. http://example.com, also used in jekyll-seo-tag
baseurl: ""
google_analytics_key:

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
tagline: "Professional Manufacturer"
author:
  name: DINGYONG
  email: sales@ding-yong.com
  phone: "+8613822066349"

# Build settings
markdown: kramdown
timezone: Asia/Shanghai

collections:
  products:
    _hide_content: false
    output: true

permalink: /:title/ # pretty

defaults:
  -
    scope:
      path: ""
      type: "products"
    values:
      layout: "product"
  -
    scope:
      path: ""
    values:
      layout: "page"
  -
    scope:
      path: "index.html"
    values:
      layout: "default"

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-leaflet
  - jekyll-feed

include:
  - .htaccess
  - _pages

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - README.md
  - LICENCE
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Contact settings

feed:
  collections:
    products:
      path: "/products.xml"

header_pages:
  - index.md
  - products.md
  - about.md
  - contact.md

# 自定义CSS
custom_css:
  - /assets/css/custom.css
